### ISSUE TITLE
Issue with VRgame.java while executing in netbeans

### ISSUE THREAD

**Issue by Shongdor** [harshitgupta1337/fogsim#14]
run:
Starting VRGame...
Exception in thread "main" java.lang.IllegalAccessError: tried to access method org.cloudbus.cloudsim.DatacenterCharacteristics.setId(I)V from class org.fog.entities.FogDevice
	at org.fog.entities.FogDevice.<init>(FogDevice.java:128)
	at org.fog.test.perfeval.VRGameFog.createFogDevice(VRGameFog.java:224)
	at org.fog.test.perfeval.VRGameFog.createFogDevices(VRGameFog.java:125)
	at org.fog.test.perfeval.VRGameFog.main(VRGameFog.java:75)
C:\Users\phantom\AppData\Local\NetBeans\Cache\8.2\executor-snippets\run.xml:53: Java returned: 1
BUILD FAILED (total time: 0 seconds)

**Comment by jua524021** [comment]
Comment this line in FogDevice class at line 27.
getCharacteristics().setId(super.getId());

**Comment by jua524021** [comment]
Sorry Line 127

**Comment by mhpardo** [comment]
> Comment this line in FogDevice class at line 27.
> getCharacteristics().setId(super.getId());

I'm having the exactly same error on my new iFogSim project on NetBeans IDE.

Anybody knows what could be?

Thanks a lot for any support.

Mário Pardo

**Comment by mohammadpasha** [comment]
getCharacteristics() from DatacenterCharacteristics class needs to be commented. Its in the begining (line 123 or so) as its not what we require in FogDevice class. Instead getCharacteristics() from FogDeviceCharacteristics class (line 210 or so) is for Fog Devices.
